/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AttestationRegistry {
  export type AttestationStruct = {
    executionId: BytesLike;
    attester: AddressLike;
    agentName: string;
    intentHash: string;
    timestamp: BigNumberish;
    verified: boolean;
  };

  export type AttestationStructOutput = [
    executionId: string,
    attester: string,
    agentName: string,
    intentHash: string,
    timestamp: bigint,
    verified: boolean
  ] & {
    executionId: string;
    attester: string;
    agentName: string;
    intentHash: string;
    timestamp: bigint;
    verified: boolean;
  };
}

export interface AttestationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTrustedAttester"
      | "attest"
      | "attestations"
      | "getAttestation"
      | "owner"
      | "renounceOwnership"
      | "revokeTrustedAttester"
      | "transferOwnership"
      | "trustedAttesters"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestationRecorded"
      | "AttesterRevoked"
      | "AttesterTrusted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addTrustedAttester",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attest",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTrustedAttester",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedAttesters",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addTrustedAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTrustedAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedAttesters",
    data: BytesLike
  ): Result;
}

export namespace AttestationRecordedEvent {
  export type InputTuple = [
    executionId: BytesLike,
    attester: AddressLike,
    agentName: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    executionId: string,
    attester: string,
    agentName: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    executionId: string;
    attester: string;
    agentName: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttesterRevokedEvent {
  export type InputTuple = [attester: AddressLike];
  export type OutputTuple = [attester: string];
  export interface OutputObject {
    attester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttesterTrustedEvent {
  export type InputTuple = [attester: AddressLike];
  export type OutputTuple = [attester: string];
  export interface OutputObject {
    attester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttestationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttestationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTrustedAttester: TypedContractMethod<
    [attester: AddressLike],
    [void],
    "nonpayable"
  >;

  attest: TypedContractMethod<
    [executionId: BytesLike, agentName: string, intentHash: string],
    [void],
    "nonpayable"
  >;

  attestations: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean] & {
        executionId: string;
        attester: string;
        agentName: string;
        intentHash: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  getAttestation: TypedContractMethod<
    [executionId: BytesLike],
    [AttestationRegistry.AttestationStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeTrustedAttester: TypedContractMethod<
    [attester: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedAttesters: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTrustedAttester"
  ): TypedContractMethod<[attester: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [executionId: BytesLike, agentName: string, intentHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, boolean] & {
        executionId: string;
        attester: string;
        agentName: string;
        intentHash: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [executionId: BytesLike],
    [AttestationRegistry.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeTrustedAttester"
  ): TypedContractMethod<[attester: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedAttesters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "AttestationRecorded"
  ): TypedContractEvent<
    AttestationRecordedEvent.InputTuple,
    AttestationRecordedEvent.OutputTuple,
    AttestationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "AttesterRevoked"
  ): TypedContractEvent<
    AttesterRevokedEvent.InputTuple,
    AttesterRevokedEvent.OutputTuple,
    AttesterRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AttesterTrusted"
  ): TypedContractEvent<
    AttesterTrustedEvent.InputTuple,
    AttesterTrustedEvent.OutputTuple,
    AttesterTrustedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AttestationRecorded(bytes32,address,string,uint256)": TypedContractEvent<
      AttestationRecordedEvent.InputTuple,
      AttestationRecordedEvent.OutputTuple,
      AttestationRecordedEvent.OutputObject
    >;
    AttestationRecorded: TypedContractEvent<
      AttestationRecordedEvent.InputTuple,
      AttestationRecordedEvent.OutputTuple,
      AttestationRecordedEvent.OutputObject
    >;

    "AttesterRevoked(address)": TypedContractEvent<
      AttesterRevokedEvent.InputTuple,
      AttesterRevokedEvent.OutputTuple,
      AttesterRevokedEvent.OutputObject
    >;
    AttesterRevoked: TypedContractEvent<
      AttesterRevokedEvent.InputTuple,
      AttesterRevokedEvent.OutputTuple,
      AttesterRevokedEvent.OutputObject
    >;

    "AttesterTrusted(address)": TypedContractEvent<
      AttesterTrustedEvent.InputTuple,
      AttesterTrustedEvent.OutputTuple,
      AttesterTrustedEvent.OutputObject
    >;
    AttesterTrusted: TypedContractEvent<
      AttesterTrustedEvent.InputTuple,
      AttesterTrustedEvent.OutputTuple,
      AttesterTrustedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
