/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ExecutionRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeExecutor"
      | "authorizedExecutors"
      | "execute"
      | "executePayment"
      | "executions"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "revokeExecutor"
      | "transferOwnership"
      | "unpause"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutionCompleted"
      | "ExecutionRequested"
      | "ExecutorAuthorized"
      | "ExecutorRevoked"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedExecutors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, string, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executePayment",
    values: [BytesLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "executions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "authorizeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ExecutionCompletedEvent {
  export type InputTuple = [
    executionId: BytesLike,
    success: boolean,
    result: BytesLike
  ];
  export type OutputTuple = [
    executionId: string,
    success: boolean,
    result: string
  ];
  export interface OutputObject {
    executionId: string;
    success: boolean;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionRequestedEvent {
  export type InputTuple = [
    executionId: BytesLike,
    requester: AddressLike,
    intentType: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    executionId: string,
    requester: string,
    intentType: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    executionId: string;
    requester: string;
    intentType: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorAuthorizedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRevokedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExecutionRouter extends BaseContract {
  connect(runner?: ContractRunner | null): ExecutionRouter;
  waitForDeployment(): Promise<this>;

  interface: ExecutionRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedExecutors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  execute: TypedContractMethod<
    [
      executionId: BytesLike,
      intentType: string,
      targetContract: AddressLike,
      callData: BytesLike
    ],
    [[boolean, string]],
    "payable"
  >;

  executePayment: TypedContractMethod<
    [
      executionId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      reason: string
    ],
    [void],
    "payable"
  >;

  executions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, boolean] & {
        requester: string;
        intentType: string;
        timestamp: bigint;
        completed: boolean;
        success: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedExecutors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      executionId: BytesLike,
      intentType: string,
      targetContract: AddressLike,
      callData: BytesLike
    ],
    [[boolean, string]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executePayment"
  ): TypedContractMethod<
    [
      executionId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      reason: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, boolean] & {
        requester: string;
        intentType: string;
        timestamp: bigint;
        completed: boolean;
        success: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ExecutionCompleted"
  ): TypedContractEvent<
    ExecutionCompletedEvent.InputTuple,
    ExecutionCompletedEvent.OutputTuple,
    ExecutionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionRequested"
  ): TypedContractEvent<
    ExecutionRequestedEvent.InputTuple,
    ExecutionRequestedEvent.OutputTuple,
    ExecutionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorAuthorized"
  ): TypedContractEvent<
    ExecutorAuthorizedEvent.InputTuple,
    ExecutorAuthorizedEvent.OutputTuple,
    ExecutorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRevoked"
  ): TypedContractEvent<
    ExecutorRevokedEvent.InputTuple,
    ExecutorRevokedEvent.OutputTuple,
    ExecutorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "ExecutionCompleted(bytes32,bool,bytes)": TypedContractEvent<
      ExecutionCompletedEvent.InputTuple,
      ExecutionCompletedEvent.OutputTuple,
      ExecutionCompletedEvent.OutputObject
    >;
    ExecutionCompleted: TypedContractEvent<
      ExecutionCompletedEvent.InputTuple,
      ExecutionCompletedEvent.OutputTuple,
      ExecutionCompletedEvent.OutputObject
    >;

    "ExecutionRequested(bytes32,address,string,uint256)": TypedContractEvent<
      ExecutionRequestedEvent.InputTuple,
      ExecutionRequestedEvent.OutputTuple,
      ExecutionRequestedEvent.OutputObject
    >;
    ExecutionRequested: TypedContractEvent<
      ExecutionRequestedEvent.InputTuple,
      ExecutionRequestedEvent.OutputTuple,
      ExecutionRequestedEvent.OutputObject
    >;

    "ExecutorAuthorized(address)": TypedContractEvent<
      ExecutorAuthorizedEvent.InputTuple,
      ExecutorAuthorizedEvent.OutputTuple,
      ExecutorAuthorizedEvent.OutputObject
    >;
    ExecutorAuthorized: TypedContractEvent<
      ExecutorAuthorizedEvent.InputTuple,
      ExecutorAuthorizedEvent.OutputTuple,
      ExecutorAuthorizedEvent.OutputObject
    >;

    "ExecutorRevoked(address)": TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;
    ExecutorRevoked: TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
